name: 'glob'
description: 'Create a glob and push to develop'
inputs:
  folder:
    description: "Folder to glob"
    required: true
  docket:
    description: "Docket file to edit"
    required: true
outputs:
  hash:
    description: "Glob hash"
    value: ${{ steps.glob.outputs.hash }}
runs:
  using: "composite"
  steps:
    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.4.0
      with:
        provider: aws
        region: 'us-east-1'
        access_key: ${{ secrets.S3_ACCESS_KEY }}
        secret_key: ${{ secrets.S3_SECRET_KEY }}
        host_base: nyc3.digitaloceanspaces.com
        host_bucket: '%(bucket)s.nyc3.digitaloceanspaces.com'
    - id: glob
      shell: bash
      run:
        ./.github/helpers/glob.sh "${{ inputs.folder }}" ${{ inputs.docket }}